### PR TITLE
Snapshot implementations can be specialized

### PR DESCRIPTION
**Pull request by ntl**
This PR depends on another PR in the `event-store-entity-store` library: https://github.com/eventide-project/event-store-entity-store/pull/2. It indirectly depends on this PR in the `entity-cache` library: https://github.com/eventide-project/entity-cache/pull/1

Previously, there was only one implementation of an entity snapshot -- a general one that used the entity class passed in by the `event-store-entity-store` library to determine the stream name for snapshots. This proved unworkable, for a few reasons:

1. In most cases, the entity class cannot be used to correctly infer the stream name. For instance, if the entity class is `SomeAggregate::Entity`, the generalized entity snapshot implementation would use `entity` as the stream name.
1. We have encountered a use case in the wild where one particular store might want to use something like redis or memcache as the storage backend.

In the course of implementing this pull request, I encountered a drawback to the `Module#prepend` approach to decorator mixins employed by the persistent store module of the `entity-cache` library. Specifically, the `EntityCache::Storage::Persistent` module uses `Module#prepend` to decorate the `#get` and `#put` methods of whatever class inherits from it via `include`. Mixing in `EntityCache::Storage::Persistent` causes abstract methods to be defined on the including class for `get` and `put`. When subclassing the specialization, this is desirable, as the specialized `get` and `put` methods are defined after the module is finished being included:

```ruby
class SomeClass
  include EntityCache::Storage::Persistent

  def get(id) # Defined after the `include` call above
  end

  def put(*) # Defined after the `include` call above
  end
end
```

When inheriting via a module, the temporal ordering is altered:

```ruby
module EntitySnapshot
  def self.included(class)
    cls.send :include, EntityCache::Storage::Persistent
  end

  def get(id) # defined before the above `included` callback is invoked by rube
  end

  def put(*) # defined before the above `included` callback is invoked by rube
  end
end
```

Specifically, when `EntitySnapshot` is included in another class, the `get` and `put` methods defined in `EntitySnapshot` are inserted into the included class's method call chain _before_ the `def self.included` method is called. Which means the virtual methods defined by including `EntityCache::Storage::Persistent` end up overriding `get` and `put`. The solution I found was to prepend the `get` and `put` methods _before_ including `EntityCache::Storage::Persistent`. It's not pretty or ideal, and may ultimately draw concerns around the entire prepending approach as a whole.

### CODE REVIEW

**Comment by sbellware** [comment]
How about not using the prepend? I don't remember the decoration implementation enough.

**Comment by ntl** [comment]
Not using the prepend would mean that a separate object owned by this library has to be used to decorate the persistent store implementation. It would also have the side effect of forcing anyone wanting to use the persistent store's telemetry to actually use that decorator to interface with their specialized persistent store. So, there would be a drawback:

```ruby
class SomeSnapshot
  include EntityCache::Storage::Persistent

  def get(*) ... end
  def put(*) ... end
end

# In a test
context "Some test that uses telemetry" do
  snapshot = SomeSnapshot.build
  decorated_snapshot = EntityCache::Storage::Persistent::Decorator.new snapshot

  # ...

  assert decorated_snapshot.telemetry.sink do
    # ...
  end
end
```

**Comment by ntl** [comment]
Actually @sbellware the more I think about this the more I realize it has nothing to do with `Module#prepend` and everything to do with invoking the `virtual` library macros inside the `def self.included` callback of a module:

```ruby
module SomeAbstractInterface
  def self.included(cls)
    cls.class_exec do
      cls.abstract :some_method
    end
  end
end

module SomeImplementation
  def self.included(cls)
    cls.class_exec do
      include SomeAbstractInterface
    end
  end

  def some_method
    "works"
  end
end

class SomeClass
  include SomeImplementation
end

SomeClass.new.some_method
=> Virtual::PureMethodError: Pure virtual (abstract) method "some_method" of SomeClass must be implemented
from /Users/ntl/Projects/obsidian/account/gems/gems/virtual-0.1.0.0/lib/virtual/pure_method.rb:11:in `block in define'
```

This is basically a distilled example of what's going on. `EventStore::EntitySnapshot` is an implementation of `EntityCache::Storage::Persistent`: it provides `get` and `put` methods. But it is itself also a module. As such, its `get` and `put` methods are inserted into `SomeClass`'s ancestry chain before its `self.included` callback is invoked. This causes the virtual method macros to be invoked after their implementations are actually included.

**Comment by sbellware** [comment]
If you're satisfied with this, then I'll defer to you. You've got a much better grasp on it at this point. Looks good for what I know about it. So, 🙈 :)

**Pull request merged**
